// All constants using globally in app
exports.AUTHENTICATION_SUCCESSFUL = "AUTHENTICATION_SUCCESSFUL";
exports.AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
exports.VALIDATION_ERROR = "BAD_REQUEST";
exports.SUCCESS = "SUCCESS";
exports.FAILED = "FAILED";
exports.DATA_NOT_FOUND = "DATA_NOT_FOUND";
exports.ERROR_OCCURED = "ERROR_OCCURED";
exports.NOT_FOUND_CODE = 404;
exports.INTERNAL_SERVER_ERROR_CODE = 500;
exports.SUCCESS_CODE = 200;
exports.BAD_REQUEST_CODE = 400;
exports.UNAUTHORIZED_CODE = 403;
exports.INVALID_LOGIN_CREDENTIALS = "INVALID_LOGIN_CREDENTIALS";
exports.INVALID_EMAILADDRESS = "INVALID_EMAILADDRESS";
exports.INVALID_SESSION = "INVALID_SESSION";
exports.INVALID_FOLLOWING = "INVALID_FOLLOWING";
exports.USER_ALREADY_FOLLOWED = "USER_ALREADY_FOLLOWED";
exports.USER_NOT_FOLLOWED = "USER_NOT_FOLLOWED";
exports.INVALID_TWEET_ID = "INVALID_TWEET_ID";
exports.UNVERIFIED_CODE = 205
exports.UNVERIFIED_EMAIL_ADDRESS = "UNVERIFIED_EMAIL_ADDRESS"
exports.INVALID_FEATURE = "INVALID_FEATURE"
exports.INVALID_MODULE = "INVALID_MODULE"
exports.APP_UPDATE_MESSAGE = "App Update: We're currently improving the app and its features. It will be available again in a short while."










